language: java

services:
  - postgresql

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sed -i 's/password=postgres/password=/g' src/main/resources/application.properties

before_script:
  - psql -c 'create database "ideaflow-test";' -U postgres

notifications:
  email:
    - janelle@openmastery.org

addons:
  hosts:
    - local.docker
